language: generic

sudo: required
services: 
    - docker

before_install:
    - docker build -t luisgo1411/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true luisgo1411/docker-react npm run test -- --coverage