language: generic

sudo: required
services: 
    - docker

before_install:
    - docker build -t luisgo1411/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true luisgo1411/docker-react npm run test -- --coverage

deploy:
    provider: elasticbeanstalk
    region: "us-west-1"
    app: "docker"
    env: "Docker-env-1"
    bucket_name: "elasticbeanstalk-us-west-1-389486198044"
    bucket_path: "docker"
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: 
        secure: $AWS_SECRET_KEY
